# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-to-aws-elasticBeanStalk
env:
  EB_PACKAGE_S3_Bucket_Name: "github-actions-aram-bucket"
  EB_APPLICATION_NAME: "github-actions"
  EB_ENVIRONMENT_NAME: "github-actions-env"
  DEPLOY_PACKAGE_NAME: "node_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-east-2"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
permissions:
  contents: read
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: CreateZipDeploymentPackage
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
      - name: Configure my AWS Credentils
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }} 
          aws-region           : ${{ env.AWS_REGION_NAME }}
      
      - name: CopyDeployPackageToS3Bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_Bucket_Name }}/


  my_cd_part:
    runs-on: ubuntu-latest
    needs: [my_ci_part]

    steps:
      - name: Configure my AWS Credentils
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }} 
          aws-region           : ${{ env.AWS_REGION_NAME }}
          
      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --source-bundle S3Bucket="github-actions-aram-bucket",S3Key="node_app_${{ github.sha }}.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"
      
      - name: Deploy New ElasticBeanStalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Ver-${{ github.sha }}"
        
#       - name: 
